/*******************************************************************************
*   Project: LoL Assembler
*
*   File: Modify_Second_UI.java
*
*   Description: @TODO
*
*   Notes: N/A
*
*   Contact: Alberto Martin Cajal, amartin.glimpse23<AT>gmail.com
*
*   URL: https://github.com/amcajal/lol_assembler
*
*   License: GNU GPL v3.0
*
*   Copyright (C) 2018 Alberto Martin Cajal
*
*   This file is part of LoL Assembler project.
*
*   LoL Assembler is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   LoL Assembler is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/


package UI;

import SourceCode.Flags;
import SourceCode.Information;
import SourceCode.Path;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class Modify_Second_UI extends javax.swing.JFrame {

    Flags fileType;
    Information information;
    Path path;

    /** Creates new form Modify_Second_UI */
    public Modify_Second_UI(Information info, Flags fT, Path p) {
        initComponents();

        Image i;
        try {
            i = ImageIO.read(getClass().getResource("/Images/lol_assembler_icon.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(LoL_assembly_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Color bgc = new Color(5,23,37);
        getContentPane().setBackground(bgc);
        
        jTextArea1.setMargin(new Insets(15,25,25,25)); // Apply margins
        jTextArea1.setEditable(false);

        //fileType = null;
        //championList = new LinkedHashMap<String, String>();
        //championList.putAll(cL);
        //championList = cL;
        information = info;
        path = p;

        if (fT.equals(fT.HOT)) {
            this.setTitle ("Modifying Hot Ones file - LoL Assembler");
            jLabel1.setText("Actual file: Hot Ones");
            fileType = fT.HOT;
        }
        else if (fT.equals(fT.LOVED)) {
            this.setTitle ("Modifying Loved Ones file - LoL Assembler");
            jLabel1.setText("Actual file: Loved Ones");
            fileType = fT.LOVED;
        }
        else if (fT.equals(fT.HATED)){
            this.setTitle ("Modifying Hated Ones file - LoL Assembler");
            jLabel1.setText("Actual file: Hated Ones");
            fileType = fT.HATED;
        }
        else { // fT is equal to COMBOS
            this.setTitle ("Modifying Combos file - LoL Assembler");
            jLabel1.setText("Actual file: Combos");
            fileType = fT.COMBOS;
        }

        

        setDefaultCloseOperation(Info_UI.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        seeButton = new javax.swing.JButton();
        modifyThirdAddButton = new javax.swing.JButton();
        modifyThirdDeleteButton = new javax.swing.JButton();
        modifyThirdDeleteAllBUtton = new javax.swing.JButton();
        modifyThirdExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 23, 37));

        jTextArea1.setBackground(new java.awt.Color(39, 40, 34));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        seeButton.setBackground(new java.awt.Color(54, 109, 90));
        seeButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        seeButton.setForeground(new java.awt.Color(255, 255, 255));
        seeButton.setText("See");
        seeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeButtonActionPerformed(evt);
            }
        });

        modifyThirdAddButton.setBackground(new java.awt.Color(54, 109, 90));
        modifyThirdAddButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        modifyThirdAddButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyThirdAddButton.setText("Add");
        modifyThirdAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySecondAddButtonActionPerformed(evt);
            }
        });

        modifyThirdDeleteButton.setBackground(new java.awt.Color(54, 109, 90));
        modifyThirdDeleteButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        modifyThirdDeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyThirdDeleteButton.setText("Delete");
        modifyThirdDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySecondDeleteButtonActionPerformed(evt);
            }
        });

        modifyThirdDeleteAllBUtton.setBackground(new java.awt.Color(54, 109, 90));
        modifyThirdDeleteAllBUtton.setFont(new java.awt.Font("Tahoma", 1, 11));
        modifyThirdDeleteAllBUtton.setForeground(new java.awt.Color(255, 255, 255));
        modifyThirdDeleteAllBUtton.setText("Delete All");
        modifyThirdDeleteAllBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySecondDeleteAllBUttonActionPerformed(evt);
            }
        });

        modifyThirdExitButton.setBackground(new java.awt.Color(30, 68, 116));
        modifyThirdExitButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        modifyThirdExitButton.setForeground(new java.awt.Color(255, 255, 255));
        modifyThirdExitButton.setText("Exit");
        modifyThirdExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySecondExitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(modifyThirdExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(modifyThirdDeleteAllBUtton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(modifyThirdDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(modifyThirdAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(seeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seeButton)
                        .addGap(18, 18, 18)
                        .addComponent(modifyThirdAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(modifyThirdDeleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(modifyThirdDeleteAllBUtton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(modifyThirdExitButton)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifySecondExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySecondExitButtonActionPerformed
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null,
                                  "Do you want to exit the modifyng window?", // Message of the window
                                  "Exiting Modifying window", // Message of the header
                                  JOptionPane.YES_NO_OPTION);

        if (selectedOption == JOptionPane.YES_OPTION) {
            System.gc(); // Release all the resources
            this.dispose();
        }
    }//GEN-LAST:event_modifySecondExitButtonActionPerformed

    private void seeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeButtonActionPerformed
        // TODO add your handling code here:
        Iterator it = null;

        switch (this.fileType) {

            case HOT:
                it = information.getHotOnes().entrySet().iterator();

                jTextArea1.setText(this.jTextArea1.getText() +
                    "******************************************************\n" +
                    "*********************  HOT ONES  *********************\n" +
                    "******************************************************\n" );

                break;

            case LOVED:
                it = information.getLovedOnes().entrySet().iterator();

                jTextArea1.setText(this.jTextArea1.getText() +
                    "******************************************************\n" +
                    "********************  LOVED ONES  ********************\n" +
                    "******************************************************\n" );

                break;

            case HATED:
                it = information.getHatedOnes().entrySet().iterator();

                jTextArea1.setText(this.jTextArea1.getText() +
                    "******************************************************\n" +
                    "********************  HATED ONES  ********************\n" +
                    "******************************************************\n" );

                break;

            case COMBOS:
                it = information.getPersonalCombos().entrySet().iterator();

                jTextArea1.setText(this.jTextArea1.getText() +
                    "******************************************************\n" +
                    "**********************  COMBOS  **********************\n" +
                    "******************************************************\n" );

                break;

            default:
                System.out.println ("Unknow file type to load (fatal error)");
                System.out.println ("No changes has been made");
                break;
        }

        if (this.fileType.equals(fileType.COMBOS)) {
            if (it.hasNext()) {
                while (it.hasNext()) {
                    Map.Entry pair = (Map.Entry)it.next();
                    //System.out.println(pair.getKey() + ":" + pair.getValue());
                    jTextArea1.setText(this.jTextArea1.getText() + "            " + 
                        pair.getKey() + ".: " + pair.getValue() + "\n" );
                }
            }
            else {
                jTextArea1.setText(this.jTextArea1.getText() + "            >> No information avaiable\n");
            }   
        }
        else {
            if (it.hasNext()) {
                while (it.hasNext()) {
                    Map.Entry pair = (Map.Entry)it.next();
                    //System.out.println(pair.getKey() + ":" + pair.getValue());
                    jTextArea1.setText(this.jTextArea1.getText() + "            " + pair.getKey() + " --> [" +
                            pair.getValue() +"]\n" );
                }
            }
            else {
                jTextArea1.setText(this.jTextArea1.getText() + "            >> No information avaiable\n");
            }
        }

        jTextArea1.setText(this.jTextArea1.getText() + "\n\n" );
        
    }//GEN-LAST:event_seeButtonActionPerformed

    private void modifySecondAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySecondAddButtonActionPerformed
        // TODO add your handling code here:
        Modify_Third_UI modifyThirdUI = new Modify_Third_UI(information, fileType.ADD, fileType, path);
        modifyThirdUI.setVisible(true);
    }//GEN-LAST:event_modifySecondAddButtonActionPerformed

    private void modifySecondDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySecondDeleteButtonActionPerformed
        // TODO add your handling code here:
        Modify_Third_UI modifyThirdPUI = new Modify_Third_UI(information, fileType.DELETE, fileType, path);
        modifyThirdPUI.setVisible(true);
    }//GEN-LAST:event_modifySecondDeleteButtonActionPerformed

    private void modifySecondDeleteAllBUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySecondDeleteAllBUttonActionPerformed
        // TODO add your handling code here:
        String message = null;
        String file = null;
        String fullOutputPath = null;
        
        switch (this.fileType) {

            case HOT:
                message = "Do you want to empty the HOT ONES file?";
                file = "Hot ones file";
                fullOutputPath = path.getMainPath() + path.getPersonalPath() + path.getHotOnesFile();
                break;
                
            case LOVED:
                message = "Do you want to empty the LOVED ONES file?";
                file = "Loved ones file";
                fullOutputPath = path.getMainPath() + path.getPersonalPath() + path.getLovedOnesFile();
                break;
                
            case HATED:
                message = "Do you want to empty the HATED ONES file?";
                file = "Hated ones file";
                fullOutputPath = path.getMainPath() + path.getPersonalPath() + path.getHatedOnesFile();
                break;

            case COMBOS:
                message = "Do you want to empty the COMBOS file?";
                file = "Combos file";
                fullOutputPath = path.getMainPath() + path.getPersonalPath() + path.getPersonalCombosFile();
                break;

            default:
                System.out.println ("Unknow file type to load (fatal error)");
                System.out.println ("No changes has been made");
                break;
        }


        int selectedOption = JOptionPane.showConfirmDialog(null,
                                  message, // Message of the window
                                  "Deleting file", // Message of the header
                                  JOptionPane.YES_NO_OPTION);

        if (selectedOption == JOptionPane.YES_OPTION) {

            // First we clear the file
            PrintWriter writer = null;
            try {
                writer = new PrintWriter(fullOutputPath);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Modify_Second_UI.class.getName()).log(Level.SEVERE, null, ex);
            }
            writer.close();

            // And then, the map from Information class
            switch (this.fileType) {

                case HOT:
                    this.information.getHotOnes().clear();
                    break;

                case LOVED:
                    this.information.getLovedOnes().clear();
                    break;

                case HATED:
                    this.information.getHatedOnes().clear();
                    break;

                case COMBOS:
                    this.information.getPersonalCombos().clear();
                    break;

                default:
                    System.out.println ("Unknow file type to load (fatal error)");
                    System.out.println ("No changes has been made");
                    break;
            }
            
            jTextArea1.setText(this.jTextArea1.getText() + " **********************************************\n"
                 + "            " + file.toUpperCase() + " has been cleared\n"
                 + " **********************************************\n\n" );

        }
   
    }//GEN-LAST:event_modifySecondDeleteAllBUttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Modify_Second_UI().setVisible(true);
                this.run();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modifyThirdAddButton;
    private javax.swing.JButton modifyThirdDeleteAllBUtton;
    private javax.swing.JButton modifyThirdDeleteButton;
    private javax.swing.JButton modifyThirdExitButton;
    private javax.swing.JButton seeButton;
    // End of variables declaration//GEN-END:variables

}
