/*******************************************************************************
*   Project: LoL Assembler
*
*   File: Modify_First_UI.java
*
*   Description: @TODO
*
*   Notes: N/A
*
*   Contact: Alberto Martin Cajal, amartin.glimpse23<AT>gmail.com
*
*   URL: https://github.com/amcajal/lol_assembler
*
*   License: GNU GPL v3.0
*
*   Copyright (C) 2018 Alberto Martin Cajal
*
*   This file is part of LoL Assembler project.
*
*   LoL Assembler is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   LoL Assembler is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/


package UI;

import SourceCode.Flags;
import SourceCode.Information;
import SourceCode.Path;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Alberto
 */
public class Modify_First_UI extends javax.swing.JFrame {

    Flags fileType;
    Information information;
    Path path;

    /** Creates new form Modify_First_UI */
    public Modify_First_UI(Information info, Path p) {
        initComponents();

        Image i;
        try {
            i = ImageIO.read(getClass().getResource("/Images/lol_assembler_icon.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(LoL_assembly_UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Color bgc = new Color(5,23,37);
        getContentPane().setBackground(bgc);

        this.setTitle ("Select file to modify - LoL Assembler");

        setDefaultCloseOperation(Info_UI.DISPOSE_ON_CLOSE);

        fileType = null;
        //championList = new LinkedHashMap<String, String>();
        //championList.putAll(cL);
        //championList = cL;
        information = info;
        path = p;
     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hotOnesButton = new javax.swing.JButton();
        lovedOnesButton = new javax.swing.JButton();
        hatedOnesButton = new javax.swing.JButton();
        combosButton = new javax.swing.JButton();
        pStrongButton1 = new javax.swing.JButton();
        pWeakButton = new javax.swing.JButton();
        pEvenButton = new javax.swing.JButton();
        pWellButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 23, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select file to modify");

        hotOnesButton.setBackground(new java.awt.Color(54, 109, 90));
        hotOnesButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hotOnesButton.setForeground(new java.awt.Color(255, 255, 255));
        hotOnesButton.setText("Hot Ones");
        hotOnesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotOnesButtonActionPerformed(evt);
            }
        });

        lovedOnesButton.setBackground(new java.awt.Color(54, 109, 90));
        lovedOnesButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lovedOnesButton.setForeground(new java.awt.Color(255, 255, 255));
        lovedOnesButton.setText("Loved Ones");
        lovedOnesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lovedOnesButtonActionPerformed(evt);
            }
        });

        hatedOnesButton.setBackground(new java.awt.Color(54, 109, 90));
        hatedOnesButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hatedOnesButton.setForeground(new java.awt.Color(255, 255, 255));
        hatedOnesButton.setText("Hated Ones");
        hatedOnesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hatedOnesButtonActionPerformed(evt);
            }
        });

        combosButton.setBackground(new java.awt.Color(54, 109, 90));
        combosButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combosButton.setForeground(new java.awt.Color(255, 255, 255));
        combosButton.setText("Combos");
        combosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosButtonActionPerformed(evt);
            }
        });

        pStrongButton1.setBackground(new java.awt.Color(54, 109, 90));
        pStrongButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pStrongButton1.setForeground(new java.awt.Color(255, 255, 255));
        pStrongButton1.setText("Personal Strong");
        pStrongButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pStrongButtonActionPerformed(evt);
            }
        });

        pWeakButton.setBackground(new java.awt.Color(54, 109, 90));
        pWeakButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pWeakButton.setForeground(new java.awt.Color(255, 255, 255));
        pWeakButton.setText("Personal Weak");
        pWeakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWeakButtonActionPerformed(evt);
            }
        });

        pEvenButton.setBackground(new java.awt.Color(54, 109, 90));
        pEvenButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pEvenButton.setForeground(new java.awt.Color(255, 255, 255));
        pEvenButton.setText("Personal Even");
        pEvenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEvenButtonActionPerformed(evt);
            }
        });

        pWellButton.setBackground(new java.awt.Color(54, 109, 90));
        pWellButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pWellButton.setForeground(new java.awt.Color(255, 255, 255));
        pWellButton.setText("Personal W. Well");
        pWellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pWellButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hatedOnesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lovedOnesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotOnesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pWellButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pEvenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pWeakButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pStrongButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotOnesButton)
                    .addComponent(pStrongButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lovedOnesButton)
                    .addComponent(pWeakButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hatedOnesButton)
                    .addComponent(pEvenButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combosButton)
                    .addComponent(pWellButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotOnesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotOnesButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_UI modifySecondUI = new Modify_Second_UI(information, fileType.HOT, path);
        modifySecondUI.setVisible(true);
    }//GEN-LAST:event_hotOnesButtonActionPerformed

    private void lovedOnesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lovedOnesButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_UI modifySecondUI = new Modify_Second_UI(information, fileType.LOVED, path);
        modifySecondUI.setVisible(true);
    }//GEN-LAST:event_lovedOnesButtonActionPerformed

    private void hatedOnesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hatedOnesButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_UI modifySecondUI = new Modify_Second_UI(information, fileType.HATED, path);
        modifySecondUI.setVisible(true);
    }//GEN-LAST:event_hatedOnesButtonActionPerformed

    private void combosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_UI modifySecondUI = new Modify_Second_UI(information, fileType.COMBOS, path);
        modifySecondUI.setVisible(true);
    }//GEN-LAST:event_combosButtonActionPerformed

    private void pStrongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pStrongButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_P_UI modifySecondPUI = new Modify_Second_P_UI(information, fileType.PSTRONG, path);
        modifySecondPUI.setVisible(true);
    }//GEN-LAST:event_pStrongButtonActionPerformed

    private void pWeakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWeakButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_P_UI modifySecondPUI = new Modify_Second_P_UI(information, fileType.PWEAK, path);
        modifySecondPUI.setVisible(true);
    }//GEN-LAST:event_pWeakButtonActionPerformed

    private void pEvenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEvenButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_P_UI modifySecondPUI = new Modify_Second_P_UI(information, fileType.PEVEN, path);
        modifySecondPUI.setVisible(true);
    }//GEN-LAST:event_pEvenButtonActionPerformed

    private void pWellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pWellButtonActionPerformed
        // TODO add your handling code here:
        Modify_Second_P_UI modifySecondPUI = new Modify_Second_P_UI(information, fileType.PWELL, path);
        modifySecondPUI.setVisible(true);
    }//GEN-LAST:event_pWellButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Modify_First_UI().setVisible(true);
                this.run();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combosButton;
    private javax.swing.JButton hatedOnesButton;
    private javax.swing.JButton hotOnesButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lovedOnesButton;
    private javax.swing.JButton pEvenButton;
    private javax.swing.JButton pStrongButton1;
    private javax.swing.JButton pWeakButton;
    private javax.swing.JButton pWellButton;
    // End of variables declaration//GEN-END:variables

}
